name: Package Addon

on:
  push:
    branches: [ main ]
    tags: [ "*" ]

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Package and release Classic
        uses: BigWigsMods/packager@v2
        with:
          args: -g classic

      - name: Package and release BCC
        uses: BigWigsMods/packager@v2
        with:
          args: -g bcc

      - name: Package and release Wrath
        uses: BigWigsMods/packager@v2
        with:
          args: -g wrath

      - name: Stage releases
        run: |
          cd .release
          mkdir -p ./ftp/
          version_re='(\w+)-(v[0-9]+(\.[0-9]+[a-z]*)*)-?([0-9a-zA-Z]+)\-'

          find . -type f -name "*.zip" | while read zip; do
            [[ $zip =~ $version_re ]]

            # 'v4.1.3b' from RXPGuides-v4.1.3b-bcc.zip
            release_version=$(echo "${BASH_REMATCH[2]}")

            # '75-' from RXPGuides-v4.1.3b-75-gdcd9f95-bcc
            release_tag=$(echo "${BASH_REMATCH[4]}")

            cp "${zip}" ./ftp/

            #If tagged release, then update latest
            if [[ "$release_tag" == "wrath" || "$release_tag" == "bcc" || "$release_tag" == "classic" ]]; then
              echo "FTP_DIR=beta" >> $GITHUB_ENV
              cp RXPGuides/CHANGELOG.md "./ftp/latest_CHANGELOG.md"
              echo $release_version > ./ftp/latest

              cp "${zip}" "./ftp/RXPGuides-latest-${release_tag}.zip"
            else
              echo "FTP_DIR=dev" >> $GITHUB_ENV
            fi
          done

          cd ..

      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .release/ftp/
          server-dir: ${{ env.FTP_DIR }}/
